packages:
  - "packages/*"
  - "external/*"
  - "external/*/packages/*"
allowBuilds:
  '@parcel/watcher': false
  better-sqlite3: set this to true or false
  esbuild: false
  sharp: true
  vue-demi: false
