import type { JsonValue } from '@mtproto-relay/bridge'

export interface QQMediaLocator {
  messageId: string
  elementId: string
  chatType: 1 | 2 | 8 | 134
  peerUid: string
  kind: 'image' | 'file' | 'voice'
  fileName: string
  fileSize?: string
  filePath?: string
  fileUuid?: string
  fileSubId?: string
  fileBizId?: number
  md5?: string
  sha?: string
  sha3?: string
  /** MD5 of the first 10 MiB, required to resolve private-file CDN URLs. */
  file10MMd5?: string
  /** QQ's original CDN URL; bridge protocol v15 can replace its expired RKey. */
  originImageUrl?: string
  /** QQ image CDN tier. 0 is original; 198 and 720 are native thumbnail specifications. */
  imageSpec?: 0 | 198 | 720
  /** Present only for native QQ video elements. 0 h264, 1 h265. */
  videoCodecFormat?: number
  avatarUin?: string
  /** UID-scoped direct avatar URL returned by QQNT. */
  avatarUrl?: string
  /** Database-backed compact preview generated by the QQNT adapter. */
  previewKey?: string
  /** Platform-local transformed asset. Never used for untouched originals. */
  cachedPath?: string
  /**
   * History placeholder whose bytes are intentionally unavailable until the
   * adapter publishes the prepared media through a message-edit event.
   */
  deferred?: true
}

export interface WireMedia {
  id: string
  kind: 'image' | 'file'
  name?: string
  mimeType?: string
  size?: number
  width?: number
  height?: number
  duration?: number
  voice?: boolean
  preview?: {
    mimeType?: string
    size: number
    width: number
    height: number
    locator: QQMediaLocator
  }
  locator: QQMediaLocator
}

export interface WireFlashTransferUploadFile {
  source: 'upload'
  name: string
  size: number
}

/** Bytes already streamed into QQ's file CDN by the upload preflight path. */
export interface WireFlashTransferUploadedFile {
  source: 'uploaded'
  name: string
  size: number
  md5: string
  sha1: string
}

export interface WireFlashTransferQQMediaFile {
  source: 'qq-media'
  name: string
  size: number
  locator: QQMediaLocator
}

export interface WireFlashTransferManifest {
  name?: string
  files: Array<WireFlashTransferUploadFile | WireFlashTransferUploadedFile | WireFlashTransferQQMediaFile>
  framing: 'length-prefixed-v1'
}

export interface WireFlashTransferResult {
  fileSetId: string
  shareLink: string
  expiresAt?: number
}

export interface WireGroupFile {
  type: 'file'
  id: string
  parentId: string
  name: string
  size: number
  uploadTime: number
  modifyTime: number
  expiresAt?: number
  downloadCount: number
  uploaderId: string
  uploaderName: string
  busId: number
  media: WireMedia
}

export interface WireGroupFileFolder {
  type: 'folder'
  id: string
  parentId: string
  name: string
  createTime: number
  modifyTime: number
  creatorId: string
  creatorName: string
  fileCount: number
}

export interface WireGroupFilePage {
  items: Array<WireGroupFile | WireGroupFileFolder>
  nextCursor?: string
  total?: number
}

export type QQStickerReference = (
  | {
      kind: 'sysface'
      faceId: string
      faceType: number
      name: string
      packId?: string
      stickerId?: string
      sourceType?: number
      stickerType?: number
      resultId?: string
      imageType?: number
      width?: number
      height?: number
      animated: true
      url?: string
    }
  | {
      kind: 'market'
      packageId: string
      stickerId: string
      name: string
      key: string
      width: number
      height: number
      animated: boolean
      mimeType?: 'image/gif' | 'image/apng' | 'image/png'
      staticPath?: string
      staticSize?: number
      dynamicPath?: string
      favoriteResId?: string
    }
  | {
      kind: 'favorite'
      resId: string
      path: string
      name: string
      md5?: string
      size?: number
      width?: number
      height?: number
      animated: boolean
      mimeType?: 'image/gif' | 'image/apng' | 'image/png' | 'image/jpeg' | 'image/webp' | 'image/bmp'
      url?: string
      locator?: QQMediaLocator
    }
) & {
  /**
   * History placeholder whose transformed bytes are intentionally unavailable
   * until the adapter publishes the prepared sticker through message-edit.
   */
  deferred?: true
}

export interface WireSticker {
  stickerId: string
  packId?: string
  title?: string
  format: 'static' | 'animated'
  mimeType: string
  width?: number
  height?: number
  size?: number
  version?: number
  reference: QQStickerReference
}

export interface WireStickerPackSummary {
  packId: string
  title: string
  count?: number
  version?: number
}

export interface WireStickerPack extends WireStickerPackSummary {
  stickers: WireSticker[]
}

export interface WireMessage {
  id: string
  sourceIds?: string[]
  conversationId: string
  senderId: string
  timestamp: number
  outgoing: boolean
  recalled?: boolean
  sender?: {
    id: string
    numericId?: string
    name: string
    alias?: string
    avatar?: WireMedia
  }
  msgSeq?: string
  telegramMessageId?: number
  telegramReplyToMessageId?: number
  /** Correlates a local HTTP send with its QQ listener echo. */
  originRequestId?: string
  replyToId?: string
  serviceAction?: { type: 'custom', text: string }
  parts: Array<
    | WireTextPart
    | { type: 'markdown', content: string }
    | { type: 'inline-keyboard', keyboard: WireInlineKeyboard }
    | { type: 'media', media: WireMedia }
    | { type: 'sticker', sticker: WireSticker }
    | { type: 'multi-forward', title: string, preview?: string, locator: WireMultiForwardLocator }
    | { type: 'card', card: WireCard }
  >
  reactionContext?: WireReactionState
}

export interface WireInlineKeyboard {
  botAppid: string
  rows: Array<{ buttons: WireInlineKeyboardButton[] }>
}

export interface WireInlineKeyboardButton {
  id: string
  label: string
  visitedLabel: string
  style: number
  type: number
  clickLimit: number
  unsupportTips: string
  data: string
  atBotShowChannelList: boolean
  permissionType: number
  specifyRoleIds: string[]
  specifyTinyids: string[]
}

export interface WireCard {
  kind: 'mini-app' | 'link' | 'music' | 'contact' | 'location' | 'application'
  title: string
  description?: string
  source?: string
  url?: string
  thumbnailUrl?: string
}

export interface WireMultiForwardLocator {
  conversationId: string
  rootMessageId: string
  parentMessageId?: string
}

export interface WireTextPart {
  type: 'text'
  text: string
  entities?: Array<
    | {
        type: 'mention'
        offset: number
        length: number
        userId: string
        numericId?: string
      }
    | {
        type: 'qq-face'
        offset: number
        length: number
        faceId: string
        faceType: number
      }
  >
}

export interface WireConversation {
  id: string
  kind: 'direct' | 'group'
  title: string
  peerUid: string
  peerUin: string
  chatType: 1 | 2 | 8 | 134
  /** QQ group message policy: 0 unspecified; 1 notify; 2 group assistant; 3 shield; 4 receive silently. */
  groupMsgMask?: 0 | 1 | 2 | 3 | 4
  avatarUrl?: string
  avatar?: WireMedia
  participantCount?: number
  selfRole?: 'owner' | 'administrator' | 'member'
  unreadCount?: number
  lastMessage?: WireMessage
  firstUnread?: { msgSeq: string, msgTime: string }
  readInboxMaxMessage?: WireMessage
}

export interface WireNativeAvsdkEvent {
  type: 'native-avsdk'
  version: 1
  callback: string
  args: unknown[]
}

export interface WireCallSignalEvent {
  type: 'call-signal'
  version: 1
  signal: 'incoming' | 'accept-requested' | 'refuse-requested' | 'logout-requested' | 'ended'
  media: 'voice' | 'unknown'
  callId: string
  conversation: WireConversation
  timestamp: number
}

export type WireRequestKind = 'friend' | 'group-join'

export type WireRequestStatus = 'pending' | 'accepted' | 'rejected'

export interface WireRequest {
  id: string
  kind: WireRequestKind
  status: WireRequestStatus
  requester: { id: string, name?: string }
  group?: { id: string, name?: string }
  message?: string
  timestamp?: string | number
  source?: 'doubt'
  reason?: string
}

export interface WireRequestPage {
  requests: WireRequest[]
  nextCursor?: string
}

export type WireEvent =
  | { type: 'message', conversation: WireConversation, message: WireMessage }
  | { type: 'message-edit', eventId: string, conversation: WireConversation, message: WireMessage }
  | { type: 'request', request: WireRequest }
  | WireCallSignalEvent
  | WireNativeAvsdkEvent
  | {
      type: 'message-delete'
      eventId: string
      conversation: WireConversation
      messageIds: string[]
      timestamp: number
    }
  | {
      type: 'message-reactions'
      eventId: string
      conversation: WireConversation
      target: { conversationId: string, messageId: string, targetId: string }
      context: WireReactionState
      timestamp: number
    }

export interface WireReactionDefinition {
  key: string
  title?: string
  presentation:
    | { type: 'emoji', emoticon: string }
    | {
        type: 'custom'
        alt: string
        resource: {
          version: number
          format: 'static' | 'video'
          mimeType: 'image/png' | 'video/webm'
          width: number
          height: number
          size?: number
          locator: JsonValue
        }
      }
}

export interface WireReactionContext extends WireReactionState {
  available: WireReactionDefinition[]
}

export interface WireReactionState {
  reactions: Array<{
    key: string
    count: number
    selected?: boolean
    recentActors?: Array<{ userId: string, timestamp?: number }>
  }>
  maxSelected: number
}

export interface WireReactionActorPage {
  state: WireReactionState
  actors: Array<{ reactionKey: string, actor: { userId: string, timestamp?: number } }>
  nextOffset?: string
}

export interface WireMemberPage {
  members: Array<{
    user: {
      id: string
      numericId?: string
      name: string
      alias?: string
      avatarUrl?: string
      avatar?: WireMedia
    }
    role: 'owner' | 'administrator' | 'member'
  }>
  total?: number
  nextCursor?: string
}
