import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import type { TlReaderMap, TlWriterMap } from '@mtcute/tl-runtime'
import { generateReaderCodeForTlEntries, generateWriterCodeForTlEntries, parseTlToEntries, type TlEntry } from '@mtcute/tl-utils'
import currentSchemaJson from '@mtcute/core/tl/api-schema.json' with { type: 'json' }
import manifestJson from '../../schema/api/manifest.json' with { type: 'json' }

interface SchemaRecord {
  requestedLayer: number
  reportedLayer?: number
  file?: string
  sha256?: string
  bytes?: number
  unavailable?: string
  error?: string
}

interface SchemaManifest {
  latestLayer: number
  layers: Record<string, SchemaRecord>
}

const manifest = manifestJson as SchemaManifest
const currentSchema = currentSchemaJson as {
  l: number
  e: Array<{ name: string, arguments?: Array<{ name: string, type: string }> }>
}

/** The API layer used by the bundled mtcute schema. */
export const CURRENT_API_LAYER = currentSchema.l

const schemaRecords = new Map<number, SchemaRecord>()
for (const record of Object.values(manifest.layers)) {
  if (record.file && record.sha256) schemaRecords.set(record.requestedLayer, record)
}
const availableLayers = [...schemaRecords.values()]
  .filter((record): record is SchemaRecord & { file: string, sha256: string } => !!record.file && !!record.sha256)
  .sort((a, b) => a.requestedLayer - b.requestedLayer)
const schemaWriterCache = new WeakMap<TlWriterMap, Map<number, TlWriterMap>>()
const readerCache = new Map<number, TlReaderMap>()
const entriesCache = new Map<number, TlEntry[]>()
let historicalReaderMap: TlReaderMap | null = null

const int53Fields = new Set(
  currentSchema.e.flatMap(entry => (entry.arguments ?? [])
    .filter(argument => argument.type === 'int53')
    .map(argument => `${entry.name}.${argument.name}`)),
)

/** Resolve unavailable/gap layers to the newest official snapshot not newer than the client. */
export function resolveApiSchemaLayer(layer: number): number | null {
  let resolved: number | null = null
  for (const record of availableLayers) {
    if (record.requestedLayer > layer) break
    resolved = record.requestedLayer
  }
  return resolved
}

/** Identify the mirrored source selected for Cordis diagnostics. */
export function resolveApiSchemaProfile(layer: number): string | null {
  const resolved = resolveApiSchemaLayer(layer)
  return resolved === null ? null : 'tdlib-history'
}

/**
 * Generate a recursive writer map from the locally mirrored schema profile for
 * the client's negotiated API layer.
 *
 * No constructor IDs or field layouts live in application code. Complete layer
 * snapshots are extracted from TDLib's local telegram_api.tl Git history by
 * scripts/sync-telegram-schemas.mjs. Writer functions are generated by the same
 * @mtcute/tl-utils code generator used elsewhere in the server. The only
 * normalization is inferred automatically from mtcute's current JSON schema:
 * fields represented as int53 by mtcute remain int53 when TL declares them as
 * long.
 */
export function getApiLayerWriterMap(base: TlWriterMap, layer: number | null): TlWriterMap {
  if (layer === null || layer === CURRENT_API_LAYER) return base
  const schemaLayer = resolveApiSchemaLayer(layer)
  if (schemaLayer === null) return base
  return getApiLayerSchemaWriterMap(base, schemaLayer)
}

/** Generate the complete writer map for tooling/tests that speak one historical schema exactly. */
export function getApiLayerSchemaWriterMap(base: TlWriterMap, layer: number): TlWriterMap {
  const schemaLayer = resolveApiSchemaLayer(layer)
  if (schemaLayer === null) return base
  let layers = schemaWriterCache.get(base)
  if (!layers) schemaWriterCache.set(base, layers = new Map())
  const cached = layers.get(schemaLayer)
  if (cached) return cached
  const code = generateWriterCodeForTlEntries(loadSchemaEntries(schemaLayer), {
    variableName: 'm',
    includePrelude: true,
    includeStaticSizes: true,
  })
  // eslint-disable-next-line no-new-func
  const generated = new Function(`${code};return m`)() as TlWriterMap
  const writerMap = Object.assign(Object.create(null), base, generated) as TlWriterMap
  layers.set(schemaLayer, writerMap)
  return writerMap
}

/** Generate a reader map from the same local official schema (useful for layer-specific clients/tests). */
export function getApiLayerReaderMap(layer: number): TlReaderMap | null {
  const schemaLayer = resolveApiSchemaLayer(layer)
  if (schemaLayer === null) return null
  const cached = readerCache.get(schemaLayer)
  if (cached) return cached
  const code = generateReaderCodeForTlEntries(loadSchemaEntries(schemaLayer), {
    variableName: 'm',
    includeMethods: true,
    includeMethodResults: true,
  })
  // eslint-disable-next-line no-new-func
  const readerMap = new Function(`${code};return m`)() as TlReaderMap
  readerCache.set(schemaLayer, readerMap)
  return readerMap
}

/**
 * Generate one server-side reader containing every distinct constructor and
 * method from every mirrored layer. Constructor IDs are the wire identity, so
 * unchanged entries naturally deduplicate while historical request IDs remain
 * available before invokeWithLayer reaches the dispatcher.
 */
export function getHistoricalApiLayerReaderMap(): TlReaderMap {
  if (historicalReaderMap) return historicalReaderMap
  const uniqueEntries = new Map<number, TlEntry>()
  for (const record of availableLayers) {
    for (const entry of loadSchemaEntries(record.requestedLayer)) uniqueEntries.set(entry.id, entry)
  }
  const code = generateReaderCodeForTlEntries([...uniqueEntries.values()], {
    variableName: 'm',
    includeMethods: true,
    includeMethodResults: true,
  })
  // eslint-disable-next-line no-new-func
  historicalReaderMap = new Function(`${code};return m`)() as TlReaderMap
  return historicalReaderMap
}

function loadSchemaEntries(schemaLayer: number): TlEntry[] {
  const cached = entriesCache.get(schemaLayer)
  if (cached) return cached
  const record = schemaRecords.get(schemaLayer)
  if (!record?.file || !record.sha256) throw new Error(`missing local Telegram schema for layer ${schemaLayer}`)
  const schema = readFileSync(new URL(`../../schema/api/${record.file}`, import.meta.url), 'utf8')
  const digest = createHash('sha256').update(schema).digest('hex')
  if (digest !== record.sha256) throw new Error(`Telegram schema layer ${schemaLayer} failed SHA-256 validation`)
  const entries = parseTlToEntries(schema, { panicOnError: true })
  normalizeMtcuteInt53(entries)
  entriesCache.set(schemaLayer, entries)
  return entries
}

function normalizeMtcuteInt53(entries: TlEntry[]): void {
  for (const entry of entries) {
    for (const argument of entry.arguments) {
      if (argument.type === 'long' && int53Fields.has(`${entry.name}.${argument.name}`)) {
        argument.type = 'int53'
      }
    }
  }
}
